ClickandCollect/apps/shop/urls.py
from django.urls import path
from .views import home, menu,redirect_buttons
app_name = "shop"
urlpatterns = [
    path('redirect_buttons/',redirect_buttons, name='redirect_buttons'),
    path("",home, name="home"),
    path("menu/",menu,name="menu"),
]

ClickandCollect/apps/users/urls.py
from django.urls import path
from .views import login,signup
app_name = "users"
urlpatterns = [
    path("login/",login, name="login"),
    path("signup/", signup, name='signup'),
]

ClickandCollect/config/urls.py
from django.contrib import admin
from django.urls import path,include


urlpatterns = [
    path('admin/', admin.site.urls,),
    path("", include("apps.shop.urls", namespace='shop')),
    path("users/",include("apps.users.urls",namespace='users')),

]

ClickandCollect/apps/cart/models.py
from django.db import models

# Create your models here.

ClickandCollect/apps/orders/models.py
from django.db import models

# Create your models here.

ClickandCollect/apps/shop/models.py
from django.db import models
from django.contrib.auth.models import User

# Create your models here.
class Menu(models.Model):
    name=models.CharField(max_length=200)
    price=models.DecimalField(max_digits=8,decimal_places=2)
    stock=models.PositiveIntegerField(default=0)
    def __str__(self):
        return self.name

class CartItem(models.Model):
    user=models.ForeignKey(User,on_delete=models.CASCADE)
    product=models.ForeignKey(Menu,on_delete=models.CASCADE)
    quantity=models.PositiveIntegerField(default=1)
    def total_price(self):
        total=self.product.price*self.quantity
        return total
    
    def __str__(self):
        return f"{self.quantity} x {self.product.name}"

ClickandCollect/apps/users/models.py
from django.db import models
from django.contrib.auth.models import User

# Create your models here.
class Profile(models.Model):
    user = models.OneToOneField(User, on_delete=models.CASCADE)
    phone = models.CharField(max_length=20)
    address = models.TextField()

ClickandCollect/apps/cart/views.py
from django.shortcuts import render

# Create your views here.

ClickandCollect/apps/orders/views.py
from django.shortcuts import render

# Create your views here.

ClickandCollect/apps/shop/views.py
from django.shortcuts import render, redirect

# Create your views here.
#def index(request):
#    message = "Hello Django"
#    return render(request, "shop/index.html", {"message": message})

def home(request):
    return render(request, "shop/home.html")

def menu(request):
    return render(request, "shop/menu.html")


def redirect_buttons(request):
    if request.method == "POST":
        action = request.POST.get("action")

        if action == "panier":
            return redirect("shop:menu")
        elif action == "compte":
            return redirect("users:login")
        
    return redirect("shop:home")    

ClickandCollect/apps/users/views.py
from django.shortcuts import render,redirect
from django.contrib.auth.models import User
from django.contrib import messages


def login(request):
    return render(request, "users/login.html")


def signup(request):
    if request.method == 'POST':
        username = request.POST.get('username')  # récupère le champ username
        email = request.POST.get('email')
        password = request.POST.get('password')

        # Vérifier si l'utilisateur existe déjà
        if User.objects.filter(username=username).exists():
            messages.error(request, "Ce nom d'utilisateur est déjà pris.")
            return redirect('signup')
        if User.objects.filter(email=email).exists():
            messages.error(request, "Cet email est déjà utilisé.")
            return redirect('signup')

        # Créer l'utilisateur
        user = User.objects.create_user(username=username, email=email, password=password)
        user.save()

        messages.success(request, "Compte créé avec succès ! Vous pouvez maintenant vous connecter.")
        return redirect('login')  # rediriger vers la page login

    return render(request, 'accounts/signup.html')  # ton template existant

ClickandCollect/apps/shop/templates/shop/home.html
 {% extends "base.html" %}
 {% load static %}
 {% include "head.html" %}



 {% block content %} 
  <!-- Product section-->
<section class="py-5">
  <div class="container px-4 px-lg-5 my-5">
    <div class="card shadow-lg border-0">
      <div class="row g-0 align-items-center">

        <!-- Image -->
        <div class="col-md-6">
          <img src="{% static 'images/couscous.jpg' %}" class="img-fluid rounded-start" alt="Couscous marocain">
        </div>

        <!-- Contenu texte -->
        <div class="col-md-6">
          <div class="card-body">
            <h1 class="card-title display-6 fw-bolder">Votre Couscous </h1>
            <h4 class="badge bg-warning text-dark mb-3">En promotion</h4>

            <div class="fs-5 mb-3">
              <span class="text-decoration-line-through">15.00 €</span>
              <span class="fw-bold text-warning ms-2">10.00 €</span>
            </div>

            <p class="card-text lead text-muted">
              Découvrez le <strong>véritable couscous marocain</strong>, un plat généreux et savoureux,
              préparé selon la tradition avec des semoules fines, légumes frais et épices parfumées 🌿.<br>
              <strong>Commandez</strong> facilement en quelques clics, récupérez votre commande et régalez-vous!.<br>
              <strong>Plusieurs variantes disponibles dès 10 € !</strong>
            </p>
            <div class="d-flex">
              <a href="{% url 'shop:menu' %}" class="btn btn-warning btn-md flex-shrink-0">
                <i class="bi-cart-fill me-4"></i>Commander maintenant
              </a>
            </div>
          </div> <!-- /card-body -->
        </div> <!-- /col-md-6 -->
      </div> <!-- /row -->
    </div> <!-- /card -->
  </div> <!-- /container -->
</section>

<!-- Related items section -->
<section class="py-5 bg-light">
  <div class="container px-4 px-lg-5 mt-5">
    <h2 class="fw-bolder mb-4 text-center">Vous pourriez aimer</h2>
    <div class="row gx-4 gx-lg-5 row-cols-2 row-cols-md-3 row-cols-xl-4 justify-content-center">

      <!-- Produit 1 -->
      <div class="col mb-5">
        <div class="card h-100">
          <img class="card-img-top" src="{% static 'images/Tajine-Viande.jpg' %}" alt="Tajine Viande" />
          <div class="card-body p-4 text-center">
            <h5 class="fw-bolder">Tajine Viande</h5>
            <p class="fw-bold text-warning fs-5">€15.00</p>
          </div>
          <div class="card-footer p-4 pt-0 border-top-0 bg-transparent">
            <div class="text-center">
              <a class="btn btn-warning w-100" href="#">Commander</a>
            </div>
          </div>
        </div>
      </div>

      <!-- Produit 2 -->
      <div class="col mb-5">
        <div class="card h-100 position-relative">
          <div class="badge bg-warning text-dark position-absolute" style="top:0.5rem; right:0.5rem">Promo</div>
          <img class="card-img-top" src="{% static 'images/Tajine-Poulet.jpg' %}" alt="Tajine Poulet" />
          <div class="card-body p-4 text-center">
            <h5 class="fw-bolder">Tajine Poulet</h5>
            <p>
              <span class="text-muted text-decoration-line-through">€15.00</span>
              <span class="fw-bold text-warning ms-2">€10.00</span>
            </p>
          </div>
          <div class="card-footer p-4 pt-0 border-top-0 bg-transparent">
            <div class="text-center">
              <a class="btn btn-warning w-100" href="#">Commander</a>
            </div>
          </div>
        </div>
      </div>

      <!-- Produit 3 -->
      <div class="col mb-5">
        <div class="card h-100 position-relative">
          <div class="badge bg-warning text-dark position-absolute" style="top:0.5rem; right:0.5rem">Promo</div>
          <img class="card-img-top" src="{% static 'images/harira.jpg' %}" alt="Harira" />
          <div class="card-body p-4 text-center">
            <h5 class="fw-bolder">Soupe "Harira"</h5>
            <p>
              <span class="text-muted text-decoration-line-through">€9.00</span>
              <span class="fw-bold text-warning ms-2">€7.00</span>
            </p>
          </div>
          <div class="card-footer p-4 pt-0 border-top-0 bg-transparent">
            <div class="text-center">
              <a class="btn btn-warning w-100" href="#">Commander</a>
            </div>
          </div>
        </div>
      </div>

      <!-- Produit 4 -->
      <div class="col mb-5">
        <div class="card h-100">
          <img class="card-img-top" src="{% static 'images/Msemen.jpg' %}" alt="Msemen" />
          <div class="card-body p-4 text-center">
            <h5 class="fw-bolder">Msemen</h5>
            <p class="fw-bold text-warning fs-5">€7.00</p>
          </div>
          <div class="card-footer p-4 pt-0 border-top-0 bg-transparent">
            <div class="text-center">
              <a class="btn btn-warning w-100" href="#">Commander</a>
            </div>
          </div>
        </div>
      </div>

    </div>
  </div>
</section>
 
 {% endblock %}

ClickandCollect/apps/shop/templates/shop/menu.html
{% extends "base.html" %}
{% load static %}
{%block content %}
<main> 
    <section class="py-3 text-center container"> 
        <div class="row py-lg-3"> 
            <div class="col-lg-6 col-md-8 mx-auto"> 
            <h1 class="titre-marocain">Nos Couscous faits maison</h1> 
            <p class="text-center lead fw-bold my-3" style="color: #C05A3E;">Choisissez votre Couscous préféré et commandez-le dès maintenant à emporter <img src="{% static 'images/delivery.jpg' %}" alt="Livraison" width="60"></p>
            </div> 
        </div> 
    </section> 
    <div class="album py-5 bg-body-tertiary">
        <div class="container"> 
            <div class="row row-cols-1 row-cols-sm-2 row-cols-md-3 g-3">
                <div class="col"> 
                    <div class="card shadow-sm">
                     <img class="card-img-top" src="{% static 'images/couscous.jpg' %}" alt="Tajine Viande" />
                        <div class="card-body"> 
                            <p class="card-text fw-bold">Couscous vegetarian</p> 
                            <div class="d-flex justify-content-between align-items-center "> 
                                <span class="fw-bold text-warning ms-2">€10.00</span> 
                                <button type="button" class="btn btn-sm btn-warning ms-5">Ajouter au panier</button> 
                                 
                            </div> 
                        </div>      
                                            
                    </div> 
                </div> 
                <div class="col"> 
                    <div class="card shadow-sm">
                        <img class="card-img-top" src="{% static 'images/viande-couscous.jpg' %}" alt="Tajine Viande" />
                            <div class="card-body"> 
                                <p class="card-text fw-bold">Couscous viande</p> 
                                <div class="d-flex justify-content-between align-items-center"> 
                                    <span class="fw-bold text-warning ms-2">€15.00</span>
                                    <button type="button" class="btn btn-sm btn-warning">Ajouter au panier</button>
                                    
                                </div> 
                            </div> 
                    </div> 
                </div> 
                    <div class="col"> 
                        <div class="card shadow-sm">
                            <img class="card-img-top" src="{% static 'images/couscous-poulet.jpg' %}" alt="Tajine Poulet" /> 
                                <div class="card-body"> 
                                <p class="card-text fw-bold">Couscous poulet</p>
                                     <div class="d-flex justify-content-between align-items-center">  
                                        <span class="fw-bold text-warning ms-2">€12.00</span>
                                        <button type="button" class="btn btn-sm btn-warning">Ajouter au panier</button> 
                                    </div> 
                                </div> 
                        </div> 
                    </div> 
                                                            
</main> 
                                                                                             
                                                                                        


{% endblock %}

ClickandCollect/apps/users/templates/users/login.html
{% extends "base.html" %}
{% load static %}
{%block content %}
<div class="col-md-4 mx-auto mt-5">
    <!-- Titres cliquables -->
    <div class="text-center mb-4">
        <h1 id="title-login" class="h4 fw-normal text-dark clickable " onclick="showLogin()">Se connecter</h1>
        <h1 id="title-register" class="h4 fw-normal text-dark clickable mb-5" onclick="showRegister()">Créer un compte</h1>
    </div>
    
    <div class="card shadow p-4 mb-5">
       <!-- Formulaire Connexion -->
        <form id="login-form">
             {% csrf_token %}
            <div class="form-floating mb-3">
                <input type="email" class="form-control" placeholder="Adresse email">
                <label>Email</label>
            </div>
            <div class="form-floating mb-3">
                <input type="password" class="form-control" placeholder="Mot de passe">
                <label>Mot de passe</label>
                <a href="#" class="forgot-link position-absolute end-0 top-50 translate-middle-y me-3">Oublié ?</a>
                                               
            </div>
            <div class="form-check text-start my-3">
                    <input class="form-check-input" type="checkbox" value="remember-me" id="checkDefault" name="remember_me">
                    <label class="form-check-label" for="checkDefault">se souvenir de moi </label>
            </div>
            <button class="btn btn-success w-100">Se connecter</button>
        </form>

        <!-- Formulaire Création compte -->
        <form id="register-form" method="POST" action="{% url 'signup' %}" style="display:none;">
             {% csrf_token %}
            <div class="form-floating mb-3">
                <input type="text"  name="username" class="form-control" placeholder="Nom d'utilisateur">
                <label>Nom d'utilisateur</label>
            </div>
            <div class="form-floating mb-3">
                <input type="email" name="email" class="form-control" placeholder="Email">
                <label>Email</label>
            </div>
            <div class="form-floating mb-3">
                <input type="password" name="password" class="form-control" placeholder="Mot de passe">
                <label>Mot de passe</label>
            </div>
            <button class="btn btn-success w-100">Créer</button>
        </form>
        

    </div>
</div>
<div style="height: 100px;"></div>

<script src="{% static 'js/scripts.js' %}"></script>
{% endblock %}

ClickandCollect/apps/users/templates/users/signup.html
{% extends "base.html" %}
{% load static %}
{%block content %}
<div class="card shadow p-4 mb-5">
       <!-- Formulaire Connexion -->
        <form id="login-form">
             {% csrf_token %}
            <div class="form-floating mb-3">
                <input type="email" class="form-control" placeholder="Adresse email">
                <label>Email</label>
            </div>
            <div class="form-floating mb-3">
                <input type="password" class="form-control" placeholder="Mot de passe">
                <label>Mot de passe</label>
                <a href="#" class="forgot-link position-absolute end-0 top-50 translate-middle-y me-3">Oublié ?</a>
                                               
            </div>
            <div class="form-check text-start my-3">
                    <input class="form-check-input" type="checkbox" value="remember-me" id="checkDefault" name="remember_me">
                    <label class="form-check-label" for="checkDefault">se souvenir de moi </label>
            </div>
            <button class="btn btn-success w-100">Se connecter</button>
        </form>

ClickandCollect/templates/base.html
 {% include "header.html" %}
 {% load static %}
 <!DOCTYPE html>
<html lang="fr">
    <body>
        <!-- Navigation-->
        <nav class="navbar navbar-expand-lg navbar-light bg-light">
            <div class="container px-4 px-lg-5">
                <a class="navbar-brand" href="#!"><img src="{% static 'images/logo-2.png' %}" alt="Logo Coscos ToGo" height="150">
                </a>
                <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation"><span class="navbar-toggler-icon"></span></button>
                <div class="collapse navbar-collapse" id="navbarSupportedContent">
                    <ul class="navbar-nav me-auto mb-2 mb-lg-0 ms-lg-4">
                        <li class="nav-item"><a class="nav-link active" aria-current="page" href="{% url 'shop:home' %}">Qui sommes nous</a></li>
                        <li class="nav-item"><a class="nav-link" href="{% url 'shop:menu' %}">Nos specialités</a></li>
                        <li class="nav-item dropdown">
                            <a class="nav-link dropdown-toggle" id="navbarDropdown" href="#" role="button" data-bs-toggle="dropdown" aria-expanded="false">Commander</a>
                            <ul class="dropdown-menu" aria-labelledby="navbarDropdown">
                                <li><a class="dropdown-item" href="#!">A emporter</a></li>
                                
                                <li><a class="dropdown-item" href="#!">En livraison</a></li>
                            </ul>
                        </li>
                    </ul>
                    <form  method="post" action="{% url 'shop:redirect_buttons' %}" class="d-flex">
                         {% csrf_token %}
                         <button name="action" value="panier" class="btn btn-outline-dark m-2" type="submit">
                            <i class="bi-cart-fill me-1"></i>
                            Panier
                            <span class="badge bg-dark text-white ms-1 rounded-pill">0</span>
                        </button>
                        <button name="action" value="compte" class="btn btn-outline-dark m-2" type="submit">
                            <i class="bi-person-fill me-1"></i>Mon compte
                        </button>
                       
                    </form>
                </div>
            </div>
        </nav>

<main>
        {% block content %} {% endblock %}
</main>
    

  {% include "footer.html" %}
  
</body>
</html>

        

ClickandCollect/templates/footer.html
 <!-- Footer-->
  {% load static %}
        <footer class="py-5 bg-dark">
            <div class="container"><p class="m-0 text-center text-white">Copyright &copy; 2026 CosCos ToGo • by <a href="https://smartech.com" target="_blank">SmarTech</a></p></div>
        </footer>
        <!-- Bootstrap core JS-->
        <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.2.3/dist/js/bootstrap.bundle.min.js"></script>
        <!-- Core theme JS-->
        <script src="{% static 'js/scripts.js' %}"></script>
    

ClickandCollect/templates/header.html
{% load static %}
    <head>
        <meta charset="utf-8" />
        <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no" />
        <meta name="description" content="" />
        <meta name="author" content="" />
        <title>Click and Collect</title>
        <!-- Favicon-->
        <link rel="icon" type="image/x-icon" href="{% static 'assets/favicon.ico' %}" />
        <!-- Bootstrap icons-->
        <link href="https://cdn.jsdelivr.net/npm/bootstrap-icons@1.5.0/font/bootstrap-icons.css" rel="stylesheet" />
        <!-- Core theme CSS (includes Bootstrap)-->
        
        <link rel="stylesheet" href="{% static 'css/styles.css' %}">    
    </head>